### ISSUE TITLE
Fails to compile on older kernels

### ISSUE THREAD

**Issue by jacob-holm** [eisenlaub/python-linkat#1]
The problem is that AT_EMPTY_PATH and AT_SYMLINK_FOLLOW don't always exist.

I managed to get it working on CentOS 6.5 (which is 2.6.32 and therefore don't have AT_EMPTY_PATH) by adding

```
#ifndef AT_EMPTY_PATH
#  define AT_EMPTY_PATH 0
#endif
```

after the #includes in linkat/ffi.py.  I assume a similar approach would work for even older kernels without AT_SYMLINK_FOLLOW.  Now 0 is clearly not the right value for these constants, so a proper fix will probably also need to check for this and remove the name at the python level.  That way any attempt to import the unsupported constant will give an ImportError.

Other than that.  Nice little package :)

**Comment by eisenlaub** [comment]
Thanks for your contribution. I'll take care of your issue and your pull request once I cured my flu. Sorry for the inconvenience and thanks for your input!

**Comment by eisenlaub** [comment]
Version 1.1 hit pypi. With this the Issue should be solved. Thus I'll close it.
